version: '3'
services:
  semawi:
    build:
      context: .
      dockerfile: Dockerfile
    image: semawi:2017_01
    ports:
      - "80:80"
    volumes:
      - semawi-images:/var/www/wiki/images/
      - ./${SEMAWI_LOGO}:/var/www/wiki/resources/assets/semawilogo.png
      - /srv/semawi/gc2smw.cfg:/opt/gc2/gc2smw.cfg
      - /srv/semawi/freetds.conf:/etc/freetds/freetds.conf
      - /srv/semawi/odbcinst.ini:/etc/odbcinst.ini
      - /srv/semawi/odbc.ini:/etc/odbc.ini
    networks:
      - wiki_network
    container_name: semawi-mediawiki
    restart: on-failure
    environment:
      - SEMAWI_WGSERVER=${SEMAWI_WGSERVER}
      - SEMAWI_SITENAME=${SEMAWI_SITENAME}
      - SEMAWI_WGSECRETKEY=${SEMAWI_WGSECRETKEY}
      - SEMAWI_WGUPGRADEKEY=${SEMAWI_WGUPGRADEKEY}
      - SEMAWI_MAXFILESIZE=${SEMAWI_MAXFILESIZE}
    depends_on:
      - wikidb
    hostname: semawi-mediawiki
  wikidb:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wiki
      - MYSQL_USER=wiki
      - MYSQL_PASSWORD=wiki
    networks:
      - wiki_network
    container_name: semawi-mysql
    hostname: semawi-mysql
    restart: on-failure

networks:
  wiki_network:
    driver: bridge

volumes:
  semawi-images:
    external: false
