version: '3.2'
services:
  cron:
    image: semawi/cron:${SEMAWI_VERSION}
    build:
      context: dockerfiles/cron
      dockerfile: Dockerfile
      args:
        - ALPINE_VERSION=${SEMAWI_ALPINE_VERSION}
    container_name: semawi-cron
    restart: unless-stopped
    depends_on:
      - semawi
    networks:
      - wiki_network
  semawi:
    build:
      context: dockerfiles/semawi
      dockerfile: Dockerfile
      args:
        - SEMAWI_HTPASS_USER=${SEMAWI_HTPASS_USER}
        - SEMAWI_HTPASS_PASS=${SEMAWI_HTPASS_PASS}
        - SEMAWI_WGSERVER=${SEMAWI_WGSERVER}
        - SEMAWI_MW_MINOR_VERSION=${SEMAWI_MW_MINOR_VERSION}
        - SEMAWI_MW_PATCH_VERSION=${SEMAWI_MW_PATCH_VERSION}
        - SMW_VERSION=${SEMAWI_SMW_VERSION}
        - SRF_VERSION=${SEMAWI_SRF_VERSION}
        - SFS_VERSION=${SEMAWI_SFS_VERSION}
        - DEBIAN_VERSION=${SEMAWI_DEBIAN_VERSION}
    image: semawi/mediawiki:${SEMAWI_VERSION}
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - semawi-images:/var/www/wiki/images/
      - ./${SEMAWI_LOGO}:/var/www/wiki/resources/assets/semawilogo.png
      - ./privkey.pem:/privkey.pem
      - ./cert.pem:/cert.pem
      - /srv/semawi/freetds.conf:/etc/freetds/freetds.conf
      - /srv/semawi/odbcinst.ini:/etc/odbcinst.ini
      - /srv/semawi/odbc.ini:/etc/odbc.ini
    networks:
      - wiki_network
    container_name: semawi-mediawiki
    restart: on-failure
    environment:
      - SEMAWI_WGSERVER=${SEMAWI_WGSERVER}
      - SEMAWI_SITENAME=${SEMAWI_SITENAME}
      - SEMAWI_WGSECRETKEY=${SEMAWI_WGSECRETKEY}
      - SEMAWI_WGUPGRADEKEY=${SEMAWI_WGUPGRADEKEY}
      - SEMAWI_MAXFILESIZE=${SEMAWI_MAXFILESIZE}
      - SEMAWI_PHP_MEM_LIMIT=${SEMAWI_PHP_MEM_LIMIT}
    depends_on:
      - wikidb
    hostname: semawi-mediawiki
    restart: unless-stopped
  wikidb:
    image: semawi/mysql:${SEMAWI_VERSION}
    build:
      context: dockerfiles/mysql
      dockerfile: Dockerfile
      args:
        - MYSQL_VERSION=${SEMAWI_MYSQL_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wiki
      - MYSQL_USER=wiki
      - MYSQL_PASSWORD=wiki
    networks:
      - wiki_network
    container_name: semawi-mysql
    hostname: semawi-mysql
    restart: unless-stopped

networks:
  wiki_network:
    driver: bridge

volumes:
  semawi-images:
    external: false
